### ISSUE TITLE
Set up a "docker compose up" workflow for archivers 2

### ISSUE THREAD

**Issue by titaniumbones** [archivers-space/docs#1]
(arbitrarily choosing this repo for app-wide issues).

Right now it's difficult to hack on the archivers 2 app b/c set up of the whole ecosystem is (a) non-trivial and (b) not extensively documented. A docker workflow (or something similar) will make it a lot easier for other devs to contribute.

**Comment by b5** [comment]
um, yes this is a big blocking issue at the moment. I've taken an initial stab at configuring docker-compose for the [archivers-api](https://github.com/archivers-space/archivers-api), with some initial documentation in the readme. @titaniumbones mind giving that a shot to see if it works locally for you? If so we can expand that pattern to all of the services & build a repo that runs the whole project locally.

**Comment by titaniumbones** [comment]
sorry, failed to get to this before departure, might not be able to do
till I get back next week.

b5 <notifications@github.com> writes:

> um, yes this is a big blocking issue at the moment. I've taken an initial stab at configuring docker-compose for the [archivers-api](https://github.com/archivers-space/archivers-api), with some initial documentation in the readme. @titaniumbones mind giving that a shot to see if it works locally for you? If so we can expand that pattern to all of the services & build a repo that runs the whole project locally.


--

**Comment by b5** [comment]
Shipped!
