### ISSUE TITLE
Up patcon's org privileges

### ISSUE THREAD

**Issue by patcon** [archivers-space/docs#3]
Hey! Just realized I can't manage tickets in some repos. Is there something you'd feel comfortable adding me to so that I have fuller access? Thanks :)

**Comment by b5** [comment]
lol how were you not an owner!? should be fixed!

**Comment by b5** [comment]
Also, please feel free to take lots & lots of ownership over this org. Close issues, open, respond to folks, so long as it's not overwhelming your workload :)
